import { useState } from 'react';
import { Card, Input } from '@/components/ui';
import { Check, CheckCircle, CreditCard, Lock, AlertCircle, Package } from 'lucide-react';

export const CheckoutPage = () => {
  const [step, setStep] = useState(0);
  const steps = [
    () => <div className="p-6"><h2 className="text-xl font-semibold text-foreground mb-6">Shipping Address</h2><form onSubmit={(e) => { e.preventDefault(); setStep(1); }} className="space-y-4"><div><label className="block text-sm font-medium text-foreground mb-2">Full Name</label><input type="text" placeholder="John Doe" className="w-full rounded-lg border-border px-3 py-2" required /></div><div><label className="block text-sm font-medium text-foreground mb-2">Address Line 1</label><input type="text" placeholder="123 Main St" className="w-full rounded-lg border-border px-3 py-2" required /></div><div className="grid grid-cols-2 gap-4"><div><label className="block text-sm font-medium text-foreground mb-2">City</label><input type="text" placeholder="City" className="w-full rounded-lg border-border px-3 py-2" required /></div><div><label className="block text-sm font-medium text-foreground mb-2">ZIP</label><input type="text" placeholder="ZIP" className="w-full rounded-lg border-border px-3 py-2" required /></div></div><button type="submit" className="w-full mt-4 px-6 py-3 bg-primary text-primary-foreground rounded">Continue to Order Review</button></form></div>,
    () => <div className="p-6"><h2 className="text-xl font-semibold text-foreground mb-6">Order Review</h2><div className="bg-white rounded-lg shadow-sm border-border p-6"><h3 className="font-semibold mb-4">Items</h3><div className="space-y-3"><div className="flex items-center gap-3 py-2 border-b border-border"><div className="w-12 h-12 rounded bg-border/50 flex items-center justify-center"><Package className="h-6 w-6 text-primary" /></div><div><div className="font-medium text-foreground">Item 1</div><div className="text-sm text-muted">$49.99 × 1</div></div><span>$49.99</span></div><div className="flex items-center gap-3 py-2"><div className="w-12 h-12 rounded bg-border/50 flex items-center justify-center"><Package className="h-6 w-6 text-primary" /></div><div><div className="font-medium text-foreground">Item 2</div><div className="text-sm text-muted">$39.99 × 1</div></div><span>$39.99</span></div></div><div className="mt-4 pt-4 border-t border-border"><div className="flex justify-between text-sm text-muted"><span>Subtotal</span><span>$89.98</span></div><div className="flex justify-between text-sm text-muted"><span>Shipping</span><span>Free</span></div><div className="flex justify-between font-bold text-primary"><span>Total</span><span>$89.98</span></div></div></div><div className="mt-8 flex gap-3"><button onClick={() => setStep(0)} className="px-4 py-2 border rounded">Previous</button><button onClick={() => setStep(2)} className="flex-1 px-6 py-3 bg-primary text-primary-foreground rounded">Continue to Payment</button></div></div>,
    () => <div className="p-6"><h2 className="text-xl font-semibold text-foreground mb-6">Payment</h2><p className="text-muted mb-6">Demo Payment — No real money will be charged.</p><Card className="p-6"><form onSubmit={(e) => { e.preventDefault(); setStep(3); }} className="space-y-6"><div><label className="block text-sm font-medium text-foreground mb-2">Cardholder Name</label><input type="text" placeholder="John Doe" className="w-full rounded-lg border-border px-3 py-2" required /></div><div><label className="block text-sm font-medium text-foreground mb-2">Demo Card Number</label><Input type="text" placeholder="4242 4242 4242 4242" className="w-full" autoComplete="cc-number" /></div><div className="grid grid-cols-2 gap-4"><div><label className="block text-sm font-medium text-foreground mb-2">Expiry (MM/YY)</label><input type="text" placeholder="12/28" className="w-full rounded-lg border-border px-3 py-2" required /></div><div><label className="block text-sm font-medium text-foreground mb-2">CVV</label><input type="text" placeholder="123" className="w-full rounded-lg border-border px-3 py-2" required /></div></div><button type="submit" className="w-full px-6 py-3 bg-primary text-primary-foreground rounded"><CreditCard className="inline h-4 w-4 mr-2" />Proceed to Payment</button></form></Card></div>,
    () => <div className="p-6 max-w-md mx-auto text-center"><CheckCircle className="h-16 w-16 text-success mx-auto mb-4" /><h2 className="text-2xl font-bold text-foreground mb-2">Order Confirmed!</h2><p className="text-muted mb-6">Your order has been successfully processed.</p><Card className="p-6 text-left"><h3 className="font-semibold mb-4">Order Details</h3><ul className="space-y-3 text-sm"><li><span className="font-medium">Order Number:</span> #ORD-2024-001</li><li><span className="font-medium">Payment Status:</span> Success</li><li><span className="font-medium">Estimated Delivery:</span> 3-5 business days</li></ul></Card><button onClick={() => window.location.href = '/'} className="mt-8 px-6 py-3 bg-primary text-primary-foreground rounded">Continue Shopping</button></div>,
  ];
  return <div className="min-h-screen bg-background pt-16"><main className="max-w-3xl mx-auto px-4"><div className="mb-6 flex items-center justify-center gap-2 text-sm text-muted"><span className={step >= 0 ? 'text-primary' : ''}><Check className="inline h-4 w-4" /> Address</span><span>→</span><span className={step >= 1 ? 'text-primary' : ''}><Check className="inline h-4 w-4" /> Review</span><span>→</span><span className={step >= 2 ? 'text-primary' : ''}><Lock className="inline h-4 w-4" /> Payment</span><span>→</span><span className={step >= 3 ? 'text-primary' : ''}><AlertCircle className="inline h-4 w-4" /> Done</span></div>{steps[step]()}</main></div>;
};
